### ISSUE TITLE
Bug :Routing Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#425]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234

- [x]  **Issue 1:When the user wants to edit the iati-identifier an unwanted message is displayed** 
Actual Result

https://user-images.githubusercontent.com/78422663/186399015-797d1246-4df6-4e99-b0aa-841f180e4707.mp4

Excepted Result
- The user should be able to edit the iati-identifier 

- [x]  **Issue 2: Back button redirects to the unwanted page**

Actual Result
https://user-images.githubusercontent.com/78422663/186398917-bbd79749-312c-4bb6-9242-1bcf08dd8c8e.mp4

Expected Result
- should redirect to the activity detail page

- [x] **Issue 3:title name link redirects to the unwanted page**
Actual Result

https://user-images.githubusercontent.com/78422663/186400950-0dc35a59-b7d7-422d-aabb-69b19384aa20.mp4

Expected Result
- should redirect to the activity detail page

- [x] **Issue 4:Any user is allowed to access all of the activities created by any user**
Actual Result
https://user-images.githubusercontent.com/78422663/186398656-2ef67182-e4e0-456b-8e7d-0614f84f159c.mp4

Expected Result
- Activities which are only of their own are to be allowed to be accessible

- [x] **Issue 5: UI breakdown in recipient region**
Actual Result
![Screenshot from 2022-08-25 11-32-05](https://user-images.githubusercontent.com/78422663/186584794-04e18bb0-ef28-4524-bd30-550947a053b5.png)

Expected Result
![Screenshot from 2022-08-24 16-18-56](https://user-images.githubusercontent.com/78422663/186397406-3356ac6a-2664-49d2-b4f7-3318da267dbf.png)

- [x] **Issue 6: unappropriate title name in edit form**
Actual Result
![Screenshot from 2022-08-24 16-07-06](https://user-images.githubusercontent.com/78422663/186395027-d970ba16-4c5b-4200-a768-755eff8a713f.png)

Expected Result
- A proper title name should be displayed

- [x]  **Issue 7: UI breakdown in humanitarian  scope**
Actual Result
![Screenshot from 2022-08-24 16-28-40](https://user-images.githubusercontent.com/78422663/186399264-20ede240-39c6-432f-a885-81507a85e646.png)

Expected Result
![Screenshot from 2022-08-24 15-57-16](https://user-images.githubusercontent.com/78422663/186399354-90d5fffd-79fd-4dc6-a61e-c4688b22bc1b.png)

- [x]  **Issue 8: UI breakdown in contact-info**
Actual Result
![Screenshot from 2022-08-24 16-05-58](https://user-images.githubusercontent.com/78422663/186394744-f820d87b-0901-46a0-8063-1d284539b295.png)

Expected Result
![Screenshot from 2022-08-24 16-04-50](https://user-images.githubusercontent.com/78422663/186394769-c0b4ca29-d09f-4f21-9def-82ccbeb9bae8.png)

- [x] **Issue 9: UI breakdown in planned-disbursement**
Actual Result
![Screenshot from 2022-08-24 16-02-27](https://user-images.githubusercontent.com/78422663/186393957-3a63ee54-ac8d-4301-83c2-cfc6ca49920f.png)

Expected Result
![Screenshot from 2022-08-24 16-04-50](https://user-images.githubusercontent.com/78422663/186394449-d102f57b-d331-4241-821c-1cefa1a5bea6.png)

- [x] **Issue 10:UI breakdown in listing page of activity, indicator, period, budget**
Actual Result
![Screenshot from 2022-08-24 16-00-51](https://user-images.githubusercontent.com/78422663/186393604-128fcb41-eb82-43e4-8e40-af760fb8e12c.png)

Expected Result
![Screenshot from 2022-08-24 16-01-24](https://user-images.githubusercontent.com/78422663/186393732-be70de42-5765-4868-a862-d52644959ed1.png)

- [x] **Issue 11: Show Full transaction  list button disappears from the activity detail page**
Actual Result
![Screenshot from 2022-08-24 15-57-16](https://user-images.githubusercontent.com/78422663/186392875-dc3c63e2-8e19-4ea0-b75f-08d618cf7c29.png)
Expected Result
![Screenshot from 2022-08-24 15-58-49](https://user-images.githubusercontent.com/78422663/186393177-dac94e2d-24ce-4b8b-82b0-a54471ff2391.png)

**Comment by man-git007** [comment]
@SauravSilwal10 
**Issues 1,2,3,4,6,11** have been fixed and deployed in the staging server. Could you please verify?
Regarding UI breakdown would hard refresh of the browser might fix it. If not @jenishshrestha could you please look into this?

**Comment by SauravSilwal10** [comment]
@man-git007  issue 3 still exists. Would you kindly review it again?

https://user-images.githubusercontent.com/78422663/186578660-bc2d98e8-0d62-44d9-8659-55f1d333c8e8.mp4

@jenishshrestha Issues 3,5,8,9,10 needs to be fixed. Please have a look.

**Comment by man-git007** [comment]
@SauravSilwal10 Issue 3 has been fixed

**Comment by jenishshrestha** [comment]
Issue 5, 7, 8, 9 and 10 have been completed and pushed to branched [408-routes-manage](https://github.com/younginnovations/iatipublisher/compare/408-routes-manage)

**Comment by SauravSilwal10** [comment]
@jenishshrestha  issue 10 planned-disbursement spacing should be reduced.
Actual Result
![Screenshot from 2022-08-29 13-23-03](https://user-images.githubusercontent.com/78422663/187151774-c0398e1a-d56f-4bf4-9ce9-29ff279bace2.png)

Expected Result

![Screenshot from 2022-08-29 14-14-28](https://user-images.githubusercontent.com/78422663/187158730-36eddf84-b4f3-4a38-865e-8f347e918b2b.png)

- [ ]Please look through this issue as well.
**The size of the publish button increases each time a user wants to create an activity.**

Actual Result

https://user-images.githubusercontent.com/78422663/187158441-3e720312-5ee1-4f0e-b510-cb7b097c8945.mp4


Expected Result
- The size of publish button should remain constant

**Comment by jenishshrestha** [comment]
@SauravSilwal10 

I have fixed issue 10 planned-disbursement in branch 408-routes-manage.

This button is already fixed in [315-activity-publish-backend-new](https://github.com/younginnovations/iatipublisher/compare/315-activity-publish-backend-new). It will be rebased into this branch soon.
