### ISSUE TITLE
Bug :Search Issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#428]
Context
- Desktop
- Chrome 102.0.5005.61

Preconditions 
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password:12345678

- [x] **Issue 1: Whenever a user types # in the search bar, the search bar continues to rotate.**

Actual Result

https://user-images.githubusercontent.com/78422663/186608675-a0665af6-b0b5-42f0-a419-ac5d07e22805.mp4

Expected Result
- A proper result should be displayed 

- [ ] **Issue 2:Even though the title name and iati-identifier do not match the searched activity, search results still display**
Steps 
- Enter 0 in the search bar 

Actual Result
- Although the Title name and iati-identifier don't include 0, the search results still show.

https://user-images.githubusercontent.com/78422663/186620132-f8caef64-ee47-4f23-a1fa-a5649658f582.mp4

Expected Result
- The search results should appear only when the title name and iati-identifier are matched.

- [x] **Issue 3 : debounce function triggered to early** 
Actual Result 

https://user-images.githubusercontent.com/78422663/186619761-3db8d357-3295-4933-8d76-5d7f2125365b.mp4

Expected Result
- call of debounce function should be delayed.

- [x] **Issue 4: when there is no search result on the detail page, pagination appears**

Actual Result
![Screenshot from 2022-08-25 14-18-10](https://user-images.githubusercontent.com/78422663/186616368-f94c63a9-3631-4816-96d0-9d8b85fd0425.png)

Expected Result
-  pagination should be removed.

**Comment by man-git007** [comment]
@SauravSilwal10 **Issue 2** has been fixed

**Comment by jenishshrestha** [comment]
All issues have been completed and pushed to branched [408-routes-manage](https://github.com/younginnovations/iatipublisher/compare/408-routes-manage)

**Comment by SauravSilwal10** [comment]
@man-git007  issue 2 still exists. Would you kindly review it again? 

https://user-images.githubusercontent.com/78422663/187142107-f6396c2f-c56c-4267-a772-67e9a878e16a.mp4



@jenishshrestha issue 1 hasn't been solved yet. Please review again.

https://user-images.githubusercontent.com/78422663/187142380-62b25abc-750b-47b4-9fc8-5b484fc989bb.mp4

**Comment by jenishshrestha** [comment]
@SauravSilwal10 

I have fixed the issue 1 with hash and pushed into branch 408-routes-manage.

**Comment by man-git007** [comment]
@SauravSilwal10 Issue 2 has been fixed. This also relates to this [comment](https://github.com/younginnovations/iatipublisher/issues/444#issuecomment-1232639077)
